name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Manual"
  comment: "automotriz"
  url: "https://dspace.itsjapon.edu.ec/xmlui/bitstream/handle/123456789/3966/MANUAL%20PRACTICO%20DEL%20AUTOMOVIL.pdf?sequence=1&isAllowed=y"
  file_name: "manual-auto-1"
  piece_size: 21 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
